# Generated by Django 5.2.4 on 2025-07-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Cars',
        ),
    ]
