# Generated by Django 5.2.4 on 2025-07-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_car_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtosalon',
            name='image',
            field=models.ImageField(blank=True, default='default/image.png', null=True, upload_to='images/'),
        ),
    ]
