# Generated by Django 5.2.4 on 2025-07-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_avtosalon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtosalon',
            name='phone',
            field=models.CharField(),
        ),
    ]
