# Generated by Django 5.2.4 on 2025-07-28 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_avtosalon_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.avtosalon'),
        ),
    ]
