# Generated by Django 5.2.4 on 2025-07-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_brand_salon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='salon',
            new_name='brand_salon',
        ),
    ]
