# Generated by Django 5.2.4 on 2025-07-28 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_salon_brand_brand_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_salon',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='app.avtosalon'),
        ),
    ]
