# Generated by Django 5.2.5 on 2025-08-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_avtosalon_created_at_avtosalon_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, default='default/car.png', null=True, upload_to='images'),
        ),
    ]
